import { SelectOptionType } from '@/types/signup.types';

export const phoneCountries: SelectOptionType[] = [
  { value: '82', label: '대한민국 +82', selected: true },
  { value: '93', label: 'Afghanistan +93', selected: false },
  { value: '355', label: 'Albania +355', selected: false },
  { value: '213', label: 'Algeria +213', selected: false },
  { value: '1', label: 'American Samoa +1', selected: false },
  { value: '376', label: 'Andorra +376', selected: false },
  { value: '244', label: 'Angola +244', selected: false },
  { value: '1', label: 'Anguilla +1', selected: false },
  { value: '1', label: 'Antigua and Barbuda +1', selected: false },
  { value: '54', label: 'Argentina +54', selected: false },
  { value: '374', label: 'Armenia +374', selected: false },
  { value: '297', label: 'Aruba +297', selected: false },
  { value: '61', label: 'Australia +61', selected: false },
  { value: '43', label: 'Austria +43', selected: false },
  { value: '994', label: 'Azerbaijan +994', selected: false },
  { value: '1', label: 'Bahamas +1', selected: false },
  { value: '973', label: 'Bahrain +973', selected: false },
  { value: '880', label: 'Bangladesh +880', selected: false },
  { value: '1', label: 'Barbados +1', selected: false },
  { value: '375', label: 'Belarus +375', selected: false },
  { value: '32', label: 'Belgium +32', selected: false },
  { value: '501', label: 'Belize +501', selected: false },
  { value: '229', label: 'Benin +229', selected: false },
  { value: '1', label: 'Bermuda +1', selected: false },
  { value: '975', label: 'Bhutan +975', selected: false },
  { value: '591', label: 'Bolivia +591', selected: false },
  { value: '387', label: 'Bosnia and Herzegovina +387', selected: false },
  { value: '267', label: 'Botswana +267', selected: false },
  { value: '55', label: 'Brazil +55', selected: false },
  {
    value: '246',
    label: 'British Indian Ocean Territory +246',
    selected: false,
  },
  { value: '673', label: 'Brunei Darussalam +673', selected: false },
  { value: '359', label: 'Bulgaria +359', selected: false },
  { value: '226', label: 'Burkina Faso +226', selected: false },
  { value: '257', label: 'Burundi +257', selected: false },
  { value: '855', label: 'Cambodia +855', selected: false },
  { value: '237', label: 'Cameroon +237', selected: false },
  { value: '1', label: 'Canada +1', selected: false },
  { value: '238', label: 'Cape Verde +238', selected: false },
  { value: '1', label: 'Cayman Islands +1', selected: false },
  { value: '236', label: 'Central African Republic +236', selected: false },
  { value: '235', label: 'Chad +235', selected: false },
  { value: '56', label: 'Chile +56', selected: false },
  { value: '86', label: "People's Republic of China +86", selected: false },
  { value: '61', label: 'Christmas Island +61', selected: false },
  { value: '61', label: 'Cocos (Keeling) Islands +61', selected: false },
  { value: '57', label: 'Colombia +57', selected: false },
  { value: '269', label: 'Comoros +269', selected: false },
  { value: '242', label: 'Republic of the Congo +242', selected: false },
  {
    value: '243',
    label: 'Democratic Republic of the Congo +243',
    selected: false,
  },
  { value: '682', label: 'Cook Islands +682', selected: false },
  { value: '506', label: 'Costa Rica +506', selected: false },
  { value: '225', label: "Cote D'Ivoire +225", selected: false },
  { value: '385', label: 'Croatia +385', selected: false },
  { value: '53', label: 'Cuba +53', selected: false },
  { value: '357', label: 'Cyprus +357', selected: false },
  { value: '420', label: 'Czech Republic +420', selected: false },
  { value: '45', label: 'Denmark +45', selected: false },
  { value: '253', label: 'Djibouti +253', selected: false },
  { value: '1', label: 'Dominica +1', selected: false },
  { value: '1', label: 'Dominican Republic +1', selected: false },
  { value: '593', label: 'Ecuador +593', selected: false },
  { value: '20', label: 'Egypt +20', selected: false },
  { value: '503', label: 'El Salvador +503', selected: false },
  { value: '240', label: 'Equatorial Guinea +240', selected: false },
  { value: '291', label: 'Eritrea +291', selected: false },
  { value: '372', label: 'Estonia +372', selected: false },
  { value: '251', label: 'Ethiopia +251', selected: false },
  { value: '500', label: 'Falkland Islands (Malvinas) +500', selected: false },
  { value: '298', label: 'Faroe Islands +298', selected: false },
  { value: '679', label: 'Fiji +679', selected: false },
  { value: '358', label: 'Finland +358', selected: false },
  { value: '33', label: 'France +33', selected: false },
  { value: '594', label: 'French Guiana +594', selected: false },
  { value: '689', label: 'French Polynesia +689', selected: false },
  { value: '241', label: 'Gabon +241', selected: false },
  { value: '220', label: 'Republic of The Gambia +220', selected: false },
  { value: '995', label: 'Georgia +995', selected: false },
  { value: '49', label: 'Germany +49', selected: false },
  { value: '233', label: 'Ghana +233', selected: false },
  { value: '350', label: 'Gibraltar +350', selected: false },
  { value: '30', label: 'Greece +30', selected: false },
  { value: '299', label: 'Greenland +299', selected: false },
  { value: '1', label: 'Grenada +1', selected: false },
  { value: '590', label: 'Guadeloupe +590', selected: false },
  { value: '1', label: 'Guam +1', selected: false },
  { value: '502', label: 'Guatemala +502', selected: false },
  { value: '224', label: 'Guinea +224', selected: false },
  { value: '245', label: 'Guinea-Bissau +245', selected: false },
  { value: '592', label: 'Guyana +592', selected: false },
  { value: '509', label: 'Haiti +509', selected: false },
  { value: '39', label: 'Holy See (Vatican City State) +39', selected: false },
  { value: '504', label: 'Honduras +504', selected: false },
  { value: '852', label: 'Hong Kong +852', selected: false },
  { value: '36', label: 'Hungary +36', selected: false },
  { value: '354', label: 'Iceland +354', selected: false },
  { value: '91', label: 'India +91', selected: false },
  { value: '62', label: 'Indonesia +62', selected: false },
  { value: '98', label: 'Islamic Republic of Iran +98', selected: false },
  { value: '964', label: 'Iraq+964', selected: false },
  { value: '353', label: 'Ireland +353', selected: false },
  { value: '972', label: 'Israel +972', selected: false },
  { value: '39', label: 'Italy +39', selected: false },
  { value: '1', label: 'Jamaica +1', selected: false },
  { value: '81', label: 'Japan +81', selected: false },
  { value: '962', label: 'Jordan +962', selected: false },
  { value: '7', label: 'Kazakhstan +7', selected: false },
  { value: '254', label: 'Kenya +254', selected: false },
  { value: '686', label: 'Kiribati +686', selected: false },
  { value: '850', label: 'North Korea +850', selected: false },
  { value: '965', label: 'Kuwait +965', selected: false },
  { value: '996', label: 'Kyrgyzstan +996', selected: false },
  {
    value: '856',
    label: "Lao People's Democratic Republic +856",
    selected: false,
  },
  { value: '371', label: 'Latvia +371', selected: false },
  { value: '961', label: 'Lebanon +961', selected: false },
  { value: '266', label: 'Lesotho +266', selected: false },
  { value: '231', label: 'Liberia +231', selected: false },
  { value: '218', label: 'Libya +218', selected: false },
  { value: '423', label: 'Liechtenstein +423', selected: false },
  { value: '370', label: 'Lithuania +370', selected: false },
  { value: '352', label: 'Luxembourg +352', selected: false },
  { value: '853', label: 'Macao +853', selected: false },
  { value: '261', label: 'Madagascar +261', selected: false },
  { value: '265', label: 'Malawi +265', selected: false },
  { value: '60', label: 'Malaysia +60', selected: false },
  { value: '960', label: 'Maldives +960', selected: false },
  { value: '223', label: 'Mali +223', selected: false },
  { value: '356', label: 'Malta +356', selected: false },
  { value: '692', label: 'Marshall Islands +692', selected: false },
  { value: '596', label: 'Martinique +596', selected: false },
  { value: '222', label: 'Mauritania +222', selected: false },
  { value: '230', label: 'Mauritius +230', selected: false },
  { value: '262', label: 'Mayotte +262', selected: false },
  { value: '52', label: 'Mexico +52', selected: false },
  {
    value: '691',
    label: 'Micronesia, Federated States of +691',
    selected: false,
  },
  { value: '373', label: 'Moldova, Republic of +373', selected: false },
  { value: '377', label: 'Monaco +377', selected: false },
  { value: '976', label: 'Mongolia +976', selected: false },
  { value: '1', label: 'Montserrat +1', selected: false },
  { value: '212', label: 'Morocco +212', selected: false },
  { value: '258', label: 'Mozambique +258', selected: false },
  { value: '95', label: 'Myanmar +95', selected: false },
  { value: '264', label: 'Namibia +264', selected: false },
  { value: '674', label: 'Nauru +674', selected: false },
  { value: '977', label: 'Nepal +977', selected: false },
  { value: '31', label: 'Netherlands +31', selected: false },
  { value: '687', label: 'New Caledonia +687', selected: false },
  { value: '64', label: 'New Zealand +64', selected: false },
  { value: '505', label: 'Nicaragua +505', selected: false },
  { value: '227', label: 'Niger +227', selected: false },
  { value: '234', label: 'Nigeria +234', selected: false },
  { value: '683', label: 'Niue +683', selected: false },
  { value: '672', label: 'Norfolk Island +672', selected: false },
  {
    value: '389',
    label: 'The Republic of North Macedonia +389',
    selected: false,
  },
  { value: '1', label: 'Northern Mariana Islands +1', selected: false },
  { value: '47', label: 'Norway +47', selected: false },
  { value: '968', label: 'Oman +968', selected: false },
  { value: '92', label: 'Pakistan +92', selected: false },
  { value: '680', label: 'Palau +680', selected: false },
  { value: '970', label: 'State of Palestine +970', selected: false },
  { value: '507', label: 'Panama +507', selected: false },
  { value: '675', label: 'Papua New Guinea +675', selected: false },
  { value: '595', label: 'Paraguay +595', selected: false },
  { value: '51', label: 'Peru +51', selected: false },
  { value: '63', label: 'Philippines +63', selected: false },
  { value: '48', label: 'Poland +48', selected: false },
  { value: '351', label: 'Portugal +351', selected: false },
  { value: '1', label: 'Puerto Rico +1', selected: false },
  { value: '974', label: 'Qatar +974', selected: false },
  { value: '262', label: 'Reunion +262', selected: false },
  { value: '40', label: 'Romania +40', selected: false },
  { value: '7', label: 'Russian Federation +7', selected: false },
  { value: '250', label: 'Rwanda +250', selected: false },
  { value: '290', label: 'Saint Helena +290', selected: false },
  { value: '1', label: 'Saint Kitts and Nevis +1', selected: false },
  { value: '1', label: 'Saint Lucia +1', selected: false },
  { value: '508', label: 'Saint Pierre and Miquelon +508', selected: false },
  { value: '1', label: 'Saint Vincent and the Grenadines +1', selected: false },
  { value: '685', label: 'Samoa +685', selected: false },
  { value: '378', label: 'San Marino +378', selected: false },
  { value: '239', label: 'Sao Tome and Principe +239', selected: false },
  { value: '966', label: 'Saudi Arabia +966', selected: false },
  { value: '221', label: 'Senegal +221', selected: false },
  { value: '248', label: 'Seychelles +248', selected: false },
  { value: '232', label: 'Sierra Leone +232', selected: false },
  { value: '65', label: 'Singapore +65', selected: false },
  { value: '421', label: 'Slovakia +421', selected: false },
  { value: '386', label: 'Slovenia +386', selected: false },
  { value: '677', label: 'Solomon Islands +677', selected: false },
  { value: '252', label: 'Somalia +252', selected: false },
  { value: '27', label: 'South Africa +27', selected: false },
  { value: '34', label: 'Spain +34', selected: false },
  { value: '94', label: 'Sri Lanka +94', selected: false },
  { value: '249', label: 'Sudan +249', selected: false },
  { value: '597', label: 'Suriname +597', selected: false },
  { value: '47', label: 'Svalbard and Jan Mayen +47', selected: false },
  { value: '268', label: 'Eswatini +268', selected: false },
  { value: '46', label: 'Sweden +46', selected: false },
  { value: '41', label: 'Switzerland +41', selected: false },
  { value: '963', label: 'Syrian Arab Republic +963', selected: false },
  { value: '886', label: 'Taiwan, Province of China +886', selected: false },
  { value: '992', label: 'Tajikistan +992', selected: false },
  { value: '255', label: 'United Republic of Tanzania +255', selected: false },
  { value: '66', label: 'Thailand +66', selected: false },
  { value: '670', label: 'Timor-Leste +670', selected: false },
  { value: '228', label: 'Togo +228', selected: false },
  { value: '690', label: 'Tokelau +690', selected: false },
  { value: '676', label: 'Tonga +676', selected: false },
  { value: '1', label: 'Trinidad and Tobago +1', selected: false },
  { value: '216', label: 'Tunisia +216', selected: false },
  { value: '90', label: 'Türkiye +90', selected: false },
  { value: '993', label: 'Turkmenistan +993', selected: false },
  { value: '1', label: 'Turks and Caicos Islands +1', selected: false },
  { value: '688', label: 'Tuvalu +688', selected: false },
  { value: '256', label: 'Uganda +256', selected: false },
  { value: '380', label: 'Ukraine +380', selected: false },
  { value: '971', label: 'United Arab Emirates +971', selected: false },
  { value: '44', label: 'United Kingdom +44', selected: false },
  { value: '1', label: 'United States of America +1', selected: false },
  { value: '598', label: 'Uruguay +598', selected: false },
  { value: '998', label: 'Uzbekistan +998', selected: false },
  { value: '678', label: 'Vanuatu +678', selected: false },
  { value: '58', label: 'Venezuela +58', selected: false },
  { value: '84', label: 'Vietnam +84', selected: false },
  { value: '1', label: 'Virgin Islands, British +1', selected: false },
  { value: '1', label: 'Virgin Islands, U.S. +1', selected: false },
  { value: '681', label: 'Wallis and Futuna +681', selected: false },
  { value: '212', label: 'Western Sahara +212', selected: false },
  { value: '967', label: 'Yemen +967', selected: false },
  { value: '260', label: 'Zambia +260', selected: false },
  { value: '263', label: 'Zimbabwe +263', selected: false },
  { value: '358', label: 'Åland Islands +358', selected: false },
  {
    value: '599',
    label: 'Bonaire, Sint Eustatius and Saba +599',
    selected: false,
  },
  { value: '599', label: 'Curaçao +599', selected: false },
  { value: '44', label: 'Guernsey +44', selected: false },
  { value: '44', label: 'Isle of Man +44', selected: false },
  { value: '44', label: 'Jersey +44', selected: false },
  { value: '382', label: 'Montenegro +382', selected: false },
  { value: '590', label: 'Saint Barthélemy +590', selected: false },
  { value: '590', label: 'Saint Martin (French part) +590', selected: false },
  { value: '381', label: 'Serbia +381', selected: false },
  { value: '1', label: 'Sint Maarten (Dutch part) +1', selected: false },
  { value: '211', label: 'South Sudan +211', selected: false },
  { value: '383', label: 'Kosovo +383', selected: false },
];
